In [29]:
import pandas as pd

In [30]:
data = {
    'Name':['Sumon','Rana','Akij','Sumon','Rana'],
    'City':['Satkhira','khulna','Motijhil Moddhopara Dhaka','Satkhira','khulna'],
    'Department': ['Hr','President','Company','hel','President'],
    'Saalry':[1000,200,24444,20,200]
}
df = pd.DataFrame(data)

In [31]:
df.duplicated().sum()

np.int64(1)

In [32]:
df.drop_duplicates()

    Name                       City Department  Saalry
0  Sumon                   Satkhira         Hr    1000
1   Rana                     khulna  President     200
2   Akij  Motijhil Moddhopara Dhaka    Company   24444
3  Sumon                   Satkhira        hel      20

In [33]:
df

    Name                       City Department  Saalry
0  Sumon                   Satkhira         Hr    1000
1   Rana                     khulna  President     200
2   Akij  Motijhil Moddhopara Dhaka    Company   24444
3  Sumon                   Satkhira        hel      20
4   Rana                     khulna  President     200

In [34]:
# permanently delete duplicates
df.drop_duplicates(inplace=True)

In [35]:
df

    Name                       City Department  Saalry
0  Sumon                   Satkhira         Hr    1000
1   Rana                     khulna  President     200
2   Akij  Motijhil Moddhopara Dhaka    Company   24444
3  Sumon                   Satkhira        hel      20

In [36]:
# droping duplicates based on col

df.drop_duplicates(subset='City')

    Name                       City Department  Saalry
0  Sumon                   Satkhira         Hr    1000
1   Rana                     khulna  President     200
2   Akij  Motijhil Moddhopara Dhaka    Company   24444

In [ ]:
# keeping last duplicate
df.drop_duplicates(subset = 'City',keep= 'last')

    Name                       City Department  Saalry
1   Rana                     khulna  President     200
2   Akij  Motijhil Moddhopara Dhaka    Company   24444
3  Sumon                   Satkhira        hel      20

In [42]:
# keeping fast duplicate
df.drop_duplicates(subset = 'City',keep= 'first')

    Name                       City Department  Saalry
0  Sumon                   Satkhira         Hr    1000
1   Rana                     khulna  President     200
2   Akij  Motijhil Moddhopara Dhaka    Company   24444