In [24]:
import pandas as pd
df = pd.read_csv('new_Data.csv')
df['Data Structure Marks'].fillna(df['Data Structure Marks'].mean(),inplace=True)
df['Algorithm Marks'].fillna(df['Algorithm Marks'].mean(),inplace=True)
df['Python Marks'].fillna(df['Python Marks'].mean(),inplace=True)
df['Total Marks'] = df[['Algorithm Marks','Data Structure Marks','Python Marks']].sum(axis=1)

C:\Users\sumon\AppData\Local\Temp\ipykernel_1744\1028340544.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Data Structure Marks'].fillna(df['Data Structure Marks'].mean(),inplace=True)
C:\Users\sumon\AppData\Local\Temp\ipykernel_1744\1028340544.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Algorithm Marks'].fillna(df['Algorithm Marks'].mean(),inplace=True)
C:\Users\sumon\AppData\Local\Temp\ipykernel_1744\1028340544.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Python Marks'].fillna(df['Python Marks'].mean(),inplace=True)

In [25]:
# min max scaling
min = df['Total Marks'].min()
max = df['Total Marks'].max()
df['Scaled_values'] = df['Total Marks'].apply(lambda x:(x-min)/(max-min))

In [26]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Region,Total Marks,A+ in DS,Passed in DS,First Name,Scaled_values
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.000000,A,True,Alif,0.708075
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,269.666667,A+,True,Fatima,0.925466
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.000000,A,True,Imran,0.763975
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.000000,A,True,Jannatul,0.335404
4,PH1005,Kamal Uddin,84.0,84.0,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,263.000000,A,False,Kamal,0.801242
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.000000,A,True,Laila,0.149068
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,245.666667,A,True,Mahmudul,0.478261
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.000000,A,True,Nadia,0.503106
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.000000,A,True,Omar,0.000000
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.000000,A,True,Priya,0.857143
10,PH1011,Rahim Sheikh,84.0,84.0,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,259.000000,A,False,Rahim,0.726708
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.000000,A,True,Sadia,0.689441
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.000000,A,True,Tanvir,0.167702
13,PH1014,Urmi Akter,84.0,84.0,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,253.666667,A,False,Urmi,0.627329
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.000000,A,True,Wahiduzzaman,0.670807
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,273.666667,A+,True,Ziaur,1.000000
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.000000,A,True,Afsana,0.987578
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.000000,A,True,Babul,0.763975
18,PH1019,Faria Rahman,84.0,84.0,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,253.666667,A,False,Faria,0.627329
19,PH1020,NaN,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.000000,A,True,Nasir,0.763975

In [27]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Region,Total Marks,A+ in DS,Passed in DS,First Name,Scaled_values
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.000000,A,True,Alif,0.708075
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,269.666667,A+,True,Fatima,0.925466
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.000000,A,True,Imran,0.763975
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.000000,A,True,Jannatul,0.335404
4,PH1005,Kamal Uddin,84.0,84.0,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,263.000000,A,False,Kamal,0.801242
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.000000,A,True,Laila,0.149068
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,245.666667,A,True,Mahmudul,0.478261
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.000000,A,True,Nadia,0.503106
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.000000,A,True,Omar,0.000000
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.000000,A,True,Priya,0.857143
10,PH1011,Rahim Sheikh,84.0,84.0,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,259.000000,A,False,Rahim,0.726708
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.000000,A,True,Sadia,0.689441
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.000000,A,True,Tanvir,0.167702
13,PH1014,Urmi Akter,84.0,84.0,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,253.666667,A,False,Urmi,0.627329
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.000000,A,True,Wahiduzzaman,0.670807
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,273.666667,A+,True,Ziaur,1.000000
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.000000,A,True,Afsana,0.987578
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.000000,A,True,Babul,0.763975
18,PH1019,Faria Rahman,84.0,84.0,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,253.666667,A,False,Faria,0.627329
19,PH1020,NaN,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.000000,A,True,Nasir,0.763975

In [28]:
#
def grading(marks):
    if marks >=260:
        return 'A+'
    elif marks >=250:
        return 'A'
    else:
        return 'A-'

In [29]:
df['Grading'] = df['Total Marks'].apply(grading)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Region,Total Marks,A+ in DS,Passed in DS,First Name,Scaled_values,Grading
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.000000,A,True,Alif,0.708075,A
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,269.666667,A+,True,Fatima,0.925466,A+
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.000000,A,True,Imran,0.763975,A+
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.000000,A,True,Jannatul,0.335404,A-
4,PH1005,Kamal Uddin,84.0,84.0,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,263.000000,A,False,Kamal,0.801242,A+
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.000000,A,True,Laila,0.149068,A-
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,245.666667,A,True,Mahmudul,0.478261,A-
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.000000,A,True,Nadia,0.503106,A-
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.000000,A,True,Omar,0.000000,A-
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.000000,A,True,Priya,0.857143,A+
10,PH1011,Rahim Sheikh,84.0,84.0,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,259.000000,A,False,Rahim,0.726708,A
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.000000,A,True,Sadia,0.689441,A
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.000000,A,True,Tanvir,0.167702,A-
13,PH1014,Urmi Akter,84.0,84.0,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,253.666667,A,False,Urmi,0.627329,A
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.000000,A,True,Wahiduzzaman,0.670807,A
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,273.666667,A+,True,Ziaur,1.000000,A+
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.000000,A,True,Afsana,0.987578,A+
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.000000,A,True,Babul,0.763975,A+
18,PH1019,Faria Rahman,84.0,84.0,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,253.666667,A,False,Faria,0.627329,A
19,PH1020,NaN,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.000000,A,True,Nasir,0.763975,A+

In [31]:
def marking_system(df):
    a = df['Python Marks'] * 3
    b = df['Algorithm Marks'] * 2
    c = df['Data Structure Marks'] * 2
    return a+b+c

df['Exceptional Marks'] = df.apply(marking_system, axis = 1)

In [32]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Region,Total Marks,A+ in DS,Passed in DS,First Name,Scaled_values,Grading,Exceptional Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.000000,A,True,Alif,0.708075,A,604.0
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,269.666667,A+,True,Fatima,0.925466,A+,625.0
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.000000,A,True,Imran,0.763975,A+,607.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.000000,A,True,Jannatul,0.335404,A-,558.0
4,PH1005,Kamal Uddin,84.0,84.0,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,263.000000,A,False,Kamal,0.801242,A+,621.0
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.000000,A,True,Laila,0.149068,A-,534.0
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,245.666667,A,True,Mahmudul,0.478261,A-,577.0
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.000000,A,True,Nadia,0.503106,A-,579.0
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.000000,A,True,Omar,0.000000,A-,516.0
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.000000,A,True,Priya,0.857143,A+,620.0
10,PH1011,Rahim Sheikh,84.0,84.0,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,259.000000,A,False,Rahim,0.726708,A,609.0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.000000,A,True,Sadia,0.689441,A,601.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.000000,A,True,Tanvir,0.167702,A-,537.0
13,PH1014,Urmi Akter,84.0,84.0,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,253.666667,A,False,Urmi,0.627329,A,593.0
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.000000,A,True,Wahiduzzaman,0.670807,A,596.0
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,273.666667,A+,True,Ziaur,1.000000,A+,633.0
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.000000,A,True,Afsana,0.987578,A+,639.0
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.000000,A,True,Babul,0.763975,A+,607.0
18,PH1019,Faria Rahman,84.0,84.0,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,253.666667,A,False,Faria,0.627329,A,593.0
19,PH1020,NaN,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.000000,A,True,Nasir,0.763975,A+,611.0