In [56]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, None, 10],
    'C': ['a', 'b', 'c', None, 'e']
})

df['A'].fillna(0,inplace=True)

df

C:\Users\sumon\AppData\Local\Temp\ipykernel_11688\3651206996.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['A'].fillna(0,inplace=True)

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
2  0.0   NaN     c
3  4.0   NaN  None
4  5.0  10.0     e

In [57]:
df

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
2  0.0   NaN     c
3  4.0   NaN  None
4  5.0  10.0     e

In [58]:
df

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
2  0.0   NaN     c
3  4.0   NaN  None
4  5.0  10.0     e

In [59]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, None, 10],
    'C': ['a', 'b', 'c', None, 'e']
})

print(df)

df['A'].fillna(0,inplace=True)
df['B'].fillna(99,inplace=True)
df['C'].fillna('Unknown',inplace=True)
print(df)

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
2  NaN   NaN     c
3  4.0   NaN  None
4  5.0  10.0     e
     A     B        C
0  1.0   5.0        a
1  2.0  99.0        b
2  0.0  99.0        c
3  4.0  99.0  Unknown
4  5.0  10.0        e

C:\Users\sumon\AppData\Local\Temp\ipykernel_11688\3621325111.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['A'].fillna(0,inplace=True)
C:\Users\sumon\AppData\Local\Temp\ipykernel_11688\3621325111.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['B'].fillna(99,inplace=True)
C:\Users\sumon\AppData\Local\Temp\ipykernel_11688\3621325111.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['C'].fillna('Unknown',inplace=True)

In [60]:
df

     A     B        C
0  1.0   5.0        a
1  2.0  99.0        b
2  0.0  99.0        c
3  4.0  99.0  Unknown
4  5.0  10.0        e

In [61]:
df.iloc[2,0] = np.nan

In [62]:
df.iloc[3,2] = None
df

     A     B     C
0  1.0   5.0     a
1  2.0  99.0     b
2  NaN  99.0     c
3  4.0  99.0  None
4  5.0  10.0     e

In [69]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, None, 10],
    'C': ['a', 'b', 'c', None, 'e']
})

print(df)

df=df.copy()
df['A'].fillna(0,inplace=True)
df['B'].fillna(99,inplace=True)
df['C'].fillna('Unknown',inplace=True)
print(df)

df = df.copy()
df.iloc[0:4,1] = 5
df.iloc[2,0] = np.nan
df.iloc[3,2] = None
print(df)

df = df.copy()
df['A'] = df['A'].fillna(3)
df.iloc[0,1] = 5
df.iloc[1:4,1] = 7.5
df['C'].fillna('Unknown',inplace=True)
print(df)

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
2  NaN   NaN     c
3  4.0   NaN  None
4  5.0  10.0     e
     A     B        C
0  1.0   5.0        a
1  2.0  99.0        b
2  0.0  99.0        c
3  4.0  99.0  Unknown
4  5.0  10.0        e
     A     B     C
0  1.0   5.0     a
1  2.0   5.0     b
2  NaN   5.0     c
3  4.0   5.0  None
4  5.0  10.0     e
     A     B        C
0  1.0   5.0        a
1  2.0   7.5        b
2  3.0   7.5        c
3  4.0   7.5  Unknown
4  5.0  10.0        e

C:\Users\sumon\AppData\Local\Temp\ipykernel_11688\228533968.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['A'].fillna(0,inplace=True)
C:\Users\sumon\AppData\Local\Temp\ipykernel_11688\228533968.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['B'].fillna(99,inplace=True)
C:\Users\sumon\AppData\Local\Temp\ipykernel_11688\228533968.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['C'].fillna('Unknown',inplace=True)
C:\Users\sumon\AppData\Local\Temp\ipykernel_11688\228533968.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['C'].fillna('Unknown',inplace=True)